// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    CompanyLocation: typeof import("./src/components/CompanyLocation.vue")["default"];
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"];
    IconCommunity: typeof import("./src/components/icons/IconCommunity.vue")["default"];
    IconDocumentation: typeof import("./src/components/icons/IconDocumentation.vue")["default"];
    IconEcosystem: typeof import("./src/components/icons/IconEcosystem.vue")["default"];
    IconSupport: typeof import("./src/components/icons/IconSupport.vue")["default"];
    IconTooling: typeof import("./src/components/icons/IconTooling.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    System: typeof import("./src/components/System/System.vue")["default"];
    SystemHeader: typeof import("./src/components/System/SystemHeader.vue")["default"];
    TagSelectBlock: typeof import("./src/components/TagSelectBlock.vue")["default"];
    TheWelcome: typeof import("./src/components/TheWelcome.vue")["default"];
    WelcomeItem: typeof import("./src/components/WelcomeItem.vue")["default"];
  }
}
