name: Deploy Frontend

on:
  workflow_call:
    inputs:
      working-directory:
        description: "Working directory"
        required: true
        type: string
      product-prefix:
        description: "Product prefix"
        required: true
        type: string
      package-list:
        description: "Package list"
        required: true
        type: string
      environment:
        description: "Environment"
        required: true
        type: string
      previous-ref:
        description: "Previous ref"
        required: true
        type: string
      current-ref:
        description: "Latest ref"
        required: true
        type: string
      temp-tag:
        description: "Temporary tag"
        required: true
        type: string
    outputs:
      package-list:
        description: "Package list"
        value: ${{ inputs.package-list }}
      environment:
        description: "Environment"
        value: ${{ inputs.environment }}
      previous-ref:
        description: "Previous ref"
        value: ${{ inputs.previous-ref }}
      current-ref:
        description: "Latest ref"
        value: ${{ inputs.current-ref }}

env:
  PRODUCT_PREFIX: ${{ inputs.product-prefix }}

jobs:
  deploy-projects:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    strategy:
      fail-fast: false
      matrix:
        package-name: ${{ fromJson(inputs.package-list) }}
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.PRODUCT_PREFIX }}-${{ matrix.package-name }}
          path: ${{ format('{0}/{1}', github.workspace, matrix.package-name) }}
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          branch: ${{ inputs.environment == 'production' && 'main' || 'preview' }}
          accountId: 07b6208da1b25129ef019d3a25cf7579
          projectName: dongjiang-${{ matrix.package-name }}
          directory: ${{ format('{0}/{1}{2}', github.workspace, matrix.package-name, matrix.package-name == 'applicant-interface' && '/h5' || '') }}
